FROM phusion/passenger-full:0.9.20

# Set correct environment variables
ENV HOME /root
ENV APP_HOME /home/app/webapp

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# PG Client, backup database, bower global
RUN apt-get update && apt-get install -y postgresql-client-9.5
RUN gem install backup -v 4.2.3
RUN npm -g install bower@1.7.9

# Workdir for bundle and bower
WORKDIR /home/app/webapp/

# Add files
ADD . /home/app/webapp/

# Change /home/app/webapp owner to user app
RUN chown -R app:app /home/app/webapp/

# Enable ssh and insecure key permanently (development)
RUN rm -f /etc/service/sshd/down
RUN /usr/sbin/enable_insecure_key

# Add init script
ADD docker/my_init.d/*.sh /etc/my_init.d/
RUN chmod +x /etc/my_init.d/*.sh

# Clean up APT when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/*
