version: '2'

services:
  database:
    image: postgres:9.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:3.0.5

  app:
    image: daniloaburto/rails-seed-services:app-latest
    ports:
     - "80:80"
    volumes:
      - bundle-data:/home/app/webapp/vendor/bundle
      - bower-data:/home/app/webapp/vendor/assets
    links:
     - database
     - redis
    depends_on:
      - ops
    environment:
      PASSENGER_APP_ENV: ${APP_ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  sidekiq:
    image: daniloaburto/rails-seed-services:sidekiq-latest
    command: /sbin/my_init -- bundle exec sidekiq -e ${SIDEKIQ_ENV} -c ${SIDEKIQ_CONCURRENCY}
    volumes:
      - bundle-data:/home/app/webapp/vendor/bundle
    links:
      - database
      - redis
    depends_on:
      - ops

  ops:
    image: daniloaburto/rails-seed-services:ops-latest
    links:
      - database
      - redis
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - bundle-data:/home/app/webapp/vendor/bundle
      - bower-data:/home/app/webapp/vendor/assets

volumes:
  bundle-data:
    driver: local
  bower-data:
    driver: local
