version: '2'

services:
  database:
    image: postgres:9.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:3.0.5

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
    volumes:
      - bundle-data:/home/app/webapp/vendor/bundle
      - bower-data:/home/app/webapp/vendor/assets
    links:
     - database
     - redis
    environment:
      PASSENGER_APP_ENV: production
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.sidekiq
  #   command: /sbin/my_init -- bundle exec sidekiq -e ${SIDEKIQ_ENVIRONMENT} -c ${SIDEKIQ_CONCURRENCY}
  #   links:
  #     - database
  #     - redis
  #
  # ops:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ops
  #   links:
  #    - database
  #    - redis
  #   environment:
  #     POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  bundle-data:
    driver: local
  bower-data:
    driver: local
