version: '2'

services:
  database:
    image: postgres:9.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.0.5

  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: docker/services/app/docker-compose/Dockerfile.dev
    ports:
     - "3000:3000"
    volumes:
     - .:/home/app/webapp
     - bundle-data:/home/app/webapp/vendor/bundle
     - bower-data:/home/app/webapp/vendor/assets
    links:
      - database
      - redis
    depends_on:
      - ops
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PASSENGER_APP_ENV: ${APP_ENV}
      TERM: xterm-256color

  sidekiq:
    build:
      context: .
      dockerfile: docker/services/sidekiq/docker-compose/Dockerfile.dev
    # command: /sbin/my_init -- bundle exec sidekiq -e ${SIDEKIQ_ENV} -c ${SIDEKIQ_CONCURRENCY}
    volumes:
     - bundle-data:/home/app/webapp/vendor/bundle
    links:
      - database
      - redis
    depends_on:
      - ops

  ops:
    build:
      context: .
      dockerfile: docker/services/ops/docker-compose/Dockerfile.dev
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - bundle-data:/home/app/webapp/vendor/bundle
      - bower-data:/home/app/webapp/vendor/assets

volumes:
  bundle-data:
    driver: local
  bower-data:
    driver: local
