version: '2'

services:
  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
     - "${POSTGRES_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.0.5

  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: /sbin/my_init -- bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
     - "3000:3000" # Rails server
     - "3001:3001" # rdebug-ide
    volumes:
     - .:/home/app/webapp
    #  - /var/lib/gems/2.2.0
    #  - /home/app/webapp/vendor/assets
    links:
      - database
      - redis
    environment:
      SERVICE: app
      ENV: ${ENV}
      PASSENGER_APP_ENV: ${ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_EXCEPTIONS_CHANNEL: ${SLACK_EXCEPTIONS_CHANNEL}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_BACKUPS_PATH: ${AWS_S3_BACKUPS_PATH}
      MAILER_URL_HOST: ${MAILER_URL_HOST}
      MAILER_URL_PORT: ${MAILER_URL_PORT}
      MAILER_FROM: ${MAILER_FROM}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASS: ${MAILER_PASS}
      TERM: xterm-256color
