version: '2'

services:
  database:
    image: postgres:9.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.0.5

  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: /sbin/my_init -- bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
     - "3000:3000"
    volumes:
     - .:/home/app/webapp
     - bundle-data:/home/app/webapp/vendor/bundle
     - bower-data:/home/app/webapp/vendor/assets
    links:
      - database
      - redis
    environment:
      SERVICE: app
      ENV: ${ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PASSENGER_APP_ENV: ${ENV}
      TERM: xterm-256color

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: /sbin/my_init -- bundle exec sidekiq -e ${ENV} -c ${SIDEKIQ_CONCURRENCY}
    environment:
      SERVICE: sidekiq
      ENV: ${ENV}
    volumes:
     - bundle-data:/home/app/webapp/vendor/bundle
    links:
      - database
      - redis

  ops:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      SERVICE: ops
      ENV: ${ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - bundle-data:/home/app/webapp/vendor/bundle
      - bower-data:/home/app/webapp/vendor/assets
    links:
      - database
      - redis

volumes:
  bundle-data:
    driver: local
  bower-data:
    driver: local
