version: '2'

services:
  database:
    image: postgres:9.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
     - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.0.5

  rails:
    container_name: rails_seed_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
     - "3000:3000"
    volumes:
     - .:/home/app/webapp
     - bundle-data:/home/app/webapp/vendor/bundle
     - bower-data:/home/app/webapp/vendor/assets
    links:
     - database
     - redis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      PASSENGER_APP_ENV: development
      TERM: xterm-256color

volumes:
  bundle-data:
    driver: local
  bower-data:
    driver: local
