postgres:
  image: postgres:9.3
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
   - "5432:5432"
  volumes:
    - /var/lib/postgresql/data

redis:
  image: redis:3.0.5

rails:
  container_name: rails_seed_app
  build: .
  dockerfile: Dockerfile.dev
  ports:
   - "3000:3000"
  volumes:
   - .:/home/app/webapp
   - /home/app/webapp/public/assets
  links:
   - postgres
   - redis
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    PASSENGER_APP_ENV: development
    TERM: xterm-256color
