version: '2'

services:
  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.0.5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    restart: always
    ports:
     - "80:80"
    links:
     - database
     - redis
    environment:
      SERVICE: app
      ENV: ${ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PASSENGER_APP_ENV: ${ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_EXCEPTIONS_CHANNEL: ${SLACK_EXCEPTIONS_CHANNEL}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_BACKUPS_PATH: ${AWS_S3_BACKUPS_PATH}
      MAILER_URL_HOST: ${MAILER_URL_HOST}
      MAILER_URL_PORT: ${MAILER_URL_PORT}
      MAILER_FROM: ${MAILER_FROM}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASS: ${MAILER_PASS}

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    command: /sbin/my_init -- bundle exec sidekiq -e ${ENV} -c ${SIDEKIQ_CONCURRENCY}
    restart: always
    links:
      - database
      - redis
    environment:
      SERVICE: sidekiq
      ENV: ${ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_EXCEPTIONS_CHANNEL: ${SLACK_EXCEPTIONS_CHANNEL}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_BACKUPS_PATH: ${AWS_S3_BACKUPS_PATH}
      MAILER_URL_HOST: ${MAILER_URL_HOST}
      MAILER_URL_PORT: ${MAILER_URL_PORT}
      MAILER_FROM: ${MAILER_FROM}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASS: ${MAILER_PASS}

  ops:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    restart: always
    links:
      - database
      - redis
    environment:
      SERVICE: ops
      ENV: ${ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_EXCEPTIONS_CHANNEL: ${SLACK_EXCEPTIONS_CHANNEL}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_BACKUPS_PATH: ${AWS_S3_BACKUPS_PATH}
      MAILER_URL_HOST: ${MAILER_URL_HOST}
      MAILER_URL_PORT: ${MAILER_URL_PORT}
      MAILER_FROM: ${MAILER_FROM}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASS: ${MAILER_PASS}
